server:
  port: 8085

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supercoding-proj3?useUnicode=true&characterEncoding=UTF-8

#  config: classpath:logback-spring-dev.xml

#datasource:
#  username: ${DATABASE_USERNAME}
#  password: ${DATABASE_PASSWORD}
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://gcp.connect.psdb.cloud:3306/yumyum?useUnicode=true&characterEncoding=UTF-8
