app: # build.gradle에서 가져오는 정보
  name: ${name}
  version: ${version}

--- # local 설정
spring:
  config:
    activate:
      on-profile: local

  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #show_sql: true
  #        format_sql: true
  #        use_sql_comments: true


  data:
    redis:
      host: 138.2.122.249
      port: 6379
      password: local

jwt:
  secret: accc9aebdfd7fc975d109d0289d68d08eaff563690791e854caa97c254365676ee94c5e05de4f5edbde0c3f63db60006b8298ac66c4e247ae80aea3f9f38347f
  access-token-validation-time: 1h
  refresh-token-validation-time: 30d

cookie:
  domain: localhost
  secure: false
  same-site: Lax

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug
